# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e8adc60a913d2744ef1d01c65862b27613d225e39a592b8643fa2ba423f88909440c67d688f444a83e951b24890e3debc0692e711710c40e7978ac03d0bb572

test:
  secret_key_base: 2ca7f689f065dc6853cffd41f4aa563e7401638c7b4454db569369f165970bdf1df69c476fd299d18d25b4558c3329f0ef4bf32ab13d7b0f949b5d614f6414d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
